name: easy_language
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  dartz: 0.10.0-nullsafety.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  introduction_screen: ^2.1.0
  language_picker:
    git:
      url: https://github.com/adam-podkowinski/flutter_language_pickers
  logger: ^1.0.0
  mocktail: ^0.1.4
  path_provider: ^2.0.2

dev_dependencies:
  bloc_test: ^8.0.2
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-MediumItalic.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish-BoldItalic.ttf
        - asset: assets/fonts/Mulish-Black.ttf
        - asset: assets/fonts/Mulish-BlackItalic.ttf
  assets:
    - assets/svgs/

flutter_native_splash:
  color: "#1863f8"
